---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: git-pull-secret
  url: ssh://git@github.com/[DEIN GITHUBACCOUNTNAME]/[DEIN REPO].git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: age-key-secret
  interval: 1m0s
  path: ./fluxcd/clusters/local
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
